### ISSUE TITLE
Foundry generator generates broken movesets when moves are learned twice

### ISSUE THREAD

**Issue by tech-ticks** [Pokerole-Software-Development/Pokerole-Data#20]
See e.g. Sableye's learnset, where Mean Look is supposed to be learned in Starter Rank and Pro Rank, but it shows up twice in Starter Rank. This could be fixed by either removing the duplicate move or changing the logic to take duplicate moves in several ranks into account.

**Comment by Willowlark** [comment]
This isn't a valid state for the data to begin with, so the fix is in the data. Sable and Kyogre have both been fixed.
