### ISSUE TITLE
Generators combining Sources

### ISSUE THREAD

**Issue by Willowlark** [Pokerole-Software-Development/Pokerole-Data#24]
Unsure if this is really needed, but the idea here is that the Version folders will only contain data straight from the book. If there are alternate datasets eventually added (Delta pokemon or something) or more likely a Leaks grouping, we'd need a way to have the generators read from both sources.

**Comment by tech-ticks** [comment]
For FoundryVTT specifically, these sources would probably be divided in multiple Compendiums that can be downloaded and added as separate modules.

**Comment by Willowlark** [comment]
That actually works for the SRD too... Not with Mongo in it's current form, but no one uses that. I think this can be closed and reopened if there's an actual case for it
