### ISSUE TITLE
Generate more accurate IDs for Foundry

### ISSUE THREAD

**Issue by tech-ticks** [Pokerole-Software-Development/Pokerole-Data#37]
The Foundry compendium generator uses the `_id` field in the JSON documents, which doesn't match Foundry's usual ID format (16 alphanumeric characters, upper- and lowercase). This might be the reason why the source ID is broken once a document is imported to the world:

<img width="389" alt="image" src="https://user-images.githubusercontent.com/65084428/213764021-804388bb-f878-498e-8e70-3e0737aaa313.png">

This is problematic since it prevents potential future data migrations where documents could be updated with new data from the compendium. Additionally, not being compliant with the expected ID format might lead to issues with the new database format introduced with v11 (not tested yet).

**Comment by Willowlark** [comment]
I ran into an issue with this on something else I was working on in foundry, I have a bit of code that can generate a better id to slap in

**Comment by Willowlark** [comment]
Implemented
